jobs:
  stage_0_job_0:
    name: nav2-mppi-controller
    runs-on: macOS-11
    strategy:
      fail-fast: false
    needs: []
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build ros-humble-nav2-mppi-controller
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-nav2-mppi-controller
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx_arm64.sh
name: build_osx
on:
  push:
    branches:
    - buildbranch_osx_arm64
